import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("confirmation keeps host generation private and exposes explicit playlist editing controls", () => {
  const source = readFileSync(new URL("../src/web/App.tsx", import.meta.url), "utf8");

  assert.match(source, /口播将在确认后生成/);
  assert.match(source, /节目内容和播放队列就绪后，会自动开始播放/);
  assert.doesNotMatch(source, /regenerateHostScripts/);
  assert.doesNotMatch(source, /hostRetryRequired/);
  assert.doesNotMatch(source, /主持口播/);
  assert.doesNotMatch(source, />重试口播</);
  assert.doesNotMatch(source, />取消重试</);
  assert.doesNotMatch(source, /onRetryHostScripts/);
  assert.doesNotMatch(source, /onEditSettings/);
  assert.match(source, /批量调整/);
  assert.match(source, /调整顺序/);
  assert.match(source, /重新推荐/);
  assert.match(source, /替换所选/);
  assert.match(source, /is-replacing/);
  assert.match(source, /替换中/);
  assert.match(source, /顺序尚未保存，保存后才能启动节目/);
  assert.match(source, /if \(view !== "confirm"\) return/);
  assert.match(source, /if \(!program\.localOnly && !apiMusic && !readyToConfirm\)/);
  assert.match(source, /连接状态尚未确认；点击启动后会实时核对并返回具体结果/);
  assert.match(source, /节目资料不完整，请退出本次节目后重新创建/);
  assert.doesNotMatch(source, /开播检查尚未通过，请检查音源、账号、本地服务与语音配置/);
  assert.match(source, /__openMusicRadioVisualizerV2/);
  assert.match(source, /meyda-audio-graph-v2/);
  assert.match(source, /analyserError/);
  assert.doesNotMatch(source, /BatchAdjustmentKind/);
  assert.doesNotMatch(source, /toggleTrackLock/);
  assert.doesNotMatch(source, />英文歌曲</);
  assert.doesNotMatch(source, />指定风格</);
  assert.doesNotMatch(source, />指定歌手</);
  assert.match(source, /完成选歌并生成口播/);
  assert.match(source, /onUndo/);
  assert.doesNotMatch(source, /onRedo/);
  assert.doesNotMatch(source, />重做</);
});
